package com.amr.client.view_main;

import com.amr.client.controller.Controller;
import com.amr.client.view_add.AddMarkaForm;
import com.amr.client.view_add.AddRezervacijaForm;
import com.amr.client.view_add.AddServisForm;
import com.amr.client.view_add.AddAutomobilForm;
import com.amr.client.view_add.AddMusterijaForm;
import com.amr.client.view_edit.EditMusterijaForm;
import com.amr.client.view_edit.EditRezervacijaForm;
import com.amr.client.view_search.SearchAutomobilForm;
import com.amr.client.view_search.SearchMarkaForm;
import com.amr.client.view_search.SearchMusterijaForm;
import com.amr.client.view_search.SearchRezervacijaForm;
import com.amr.common.domain.Radnik;
import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Nebojsa Brankovic
 */
public class MainMenuForm extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuForm
     */
    private Controller c;
    private Radnik radnik;

    public MainMenuForm(Radnik radnik) {
        initComponents();
        this.radnik = radnik;
        c = new Controller();
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPozadina = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButtonRezervacijaDodaj = new javax.swing.JButton();
        jButtonRezervacijaPretrazi = new javax.swing.JButton();
        jButtonRezervacijaIzmeni = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonAutoDodaj = new javax.swing.JButton();
        jButtonAutoPretrazi = new javax.swing.JButton();
        jButtonAutoServis = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonMusterijaDodaj = new javax.swing.JButton();
        jButtonMusterijaPretrazi = new javax.swing.JButton();
        jButtonMusterijaIzmeni = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButtonMarkaDodaj = new javax.swing.JButton();
        jButtonMarkaPretrazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Automehanicarska radnja");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabelPozadina.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 2, true));
        jPanel3.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Rezervacija");

        jButtonRezervacijaDodaj.setBackground(new java.awt.Color(0, 255, 255));
        jButtonRezervacijaDodaj.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonRezervacijaDodaj.setForeground(new java.awt.Color(0, 0, 0));
        jButtonRezervacijaDodaj.setText("Dodaj");
        jButtonRezervacijaDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRezervacijaDodajActionPerformed(evt);
            }
        });

        jButtonRezervacijaPretrazi.setBackground(new java.awt.Color(0, 255, 255));
        jButtonRezervacijaPretrazi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonRezervacijaPretrazi.setForeground(new java.awt.Color(0, 0, 0));
        jButtonRezervacijaPretrazi.setText("Pretrazi");
        jButtonRezervacijaPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRezervacijaPretraziActionPerformed(evt);
            }
        });

        jButtonRezervacijaIzmeni.setBackground(new java.awt.Color(0, 255, 255));
        jButtonRezervacijaIzmeni.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonRezervacijaIzmeni.setForeground(new java.awt.Color(0, 0, 0));
        jButtonRezervacijaIzmeni.setText("Izmeni");
        jButtonRezervacijaIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRezervacijaIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonRezervacijaDodaj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRezervacijaPretrazi, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonRezervacijaIzmeni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(62, 62, 62))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(50, 50, 50)
                .addComponent(jButtonRezervacijaDodaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jButtonRezervacijaPretrazi)
                .addGap(56, 56, 56)
                .addComponent(jButtonRezervacijaIzmeni)
                .addGap(49, 49, 49))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 2, true));
        jPanel2.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Automobil");

        jButtonAutoDodaj.setBackground(new java.awt.Color(0, 255, 255));
        jButtonAutoDodaj.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonAutoDodaj.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAutoDodaj.setText("Dodaj");
        jButtonAutoDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAutoDodajActionPerformed(evt);
            }
        });

        jButtonAutoPretrazi.setBackground(new java.awt.Color(0, 255, 255));
        jButtonAutoPretrazi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonAutoPretrazi.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAutoPretrazi.setText("Pretrazi");
        jButtonAutoPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAutoPretraziActionPerformed(evt);
            }
        });

        jButtonAutoServis.setBackground(new java.awt.Color(0, 255, 255));
        jButtonAutoServis.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonAutoServis.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAutoServis.setText("Servis");
        jButtonAutoServis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAutoServisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonAutoPretrazi)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonAutoDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonAutoServis, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addComponent(jButtonAutoDodaj)
                .addGap(56, 56, 56)
                .addComponent(jButtonAutoPretrazi)
                .addGap(56, 56, 56)
                .addComponent(jButtonAutoServis)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 2, true));
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Musterija");

        jButtonMusterijaDodaj.setBackground(new java.awt.Color(0, 255, 255));
        jButtonMusterijaDodaj.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonMusterijaDodaj.setForeground(new java.awt.Color(0, 0, 0));
        jButtonMusterijaDodaj.setText("Dodaj");
        jButtonMusterijaDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMusterijaDodajActionPerformed(evt);
            }
        });

        jButtonMusterijaPretrazi.setBackground(new java.awt.Color(0, 255, 255));
        jButtonMusterijaPretrazi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonMusterijaPretrazi.setForeground(new java.awt.Color(0, 0, 0));
        jButtonMusterijaPretrazi.setText("Pretrazi");
        jButtonMusterijaPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMusterijaPretraziActionPerformed(evt);
            }
        });

        jButtonMusterijaIzmeni.setBackground(new java.awt.Color(0, 255, 255));
        jButtonMusterijaIzmeni.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonMusterijaIzmeni.setForeground(new java.awt.Color(0, 0, 0));
        jButtonMusterijaIzmeni.setText("Izmeni");
        jButtonMusterijaIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMusterijaIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1)
                        .addGap(0, 70, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonMusterijaDodaj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMusterijaIzmeni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMusterijaPretrazi, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(jButtonMusterijaDodaj)
                .addGap(56, 56, 56)
                .addComponent(jButtonMusterijaPretrazi)
                .addGap(56, 56, 56)
                .addComponent(jButtonMusterijaIzmeni)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 2, true));
        jPanel4.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Marka");

        jButtonMarkaDodaj.setBackground(new java.awt.Color(0, 255, 255));
        jButtonMarkaDodaj.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonMarkaDodaj.setForeground(new java.awt.Color(0, 0, 0));
        jButtonMarkaDodaj.setText("Dodaj");
        jButtonMarkaDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMarkaDodajActionPerformed(evt);
            }
        });

        jButtonMarkaPretrazi.setBackground(new java.awt.Color(0, 255, 255));
        jButtonMarkaPretrazi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonMarkaPretrazi.setForeground(new java.awt.Color(0, 0, 0));
        jButtonMarkaPretrazi.setText("Pretrazi");
        jButtonMarkaPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMarkaPretraziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonMarkaDodaj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMarkaPretrazi, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel4)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(50, 50, 50)
                .addComponent(jButtonMarkaDodaj)
                .addGap(56, 56, 56)
                .addComponent(jButtonMarkaPretrazi)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelPozadina))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelPozadina)
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        c.quit(radnik);
    }//GEN-LAST:event_formWindowClosed

    private void jButtonMusterijaDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMusterijaDodajActionPerformed
        AddMusterijaForm amf = new AddMusterijaForm();
        amf.setVisible(true);
    }//GEN-LAST:event_jButtonMusterijaDodajActionPerformed

    private void jButtonMusterijaPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMusterijaPretraziActionPerformed
        SearchMusterijaForm smf = new SearchMusterijaForm();
        smf.setVisible(true);
    }//GEN-LAST:event_jButtonMusterijaPretraziActionPerformed

    private void jButtonMusterijaIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMusterijaIzmeniActionPerformed
        EditMusterijaForm emf = new EditMusterijaForm();
        emf.setVisible(true);
    }//GEN-LAST:event_jButtonMusterijaIzmeniActionPerformed

    private void jButtonAutoDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAutoDodajActionPerformed
        AddAutomobilForm aaf = new AddAutomobilForm();
        aaf.setVisible(true);
    }//GEN-LAST:event_jButtonAutoDodajActionPerformed

    private void jButtonAutoPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAutoPretraziActionPerformed
        SearchAutomobilForm saf = new SearchAutomobilForm();
        saf.setVisible(true);
    }//GEN-LAST:event_jButtonAutoPretraziActionPerformed

    private void jButtonAutoServisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAutoServisActionPerformed
        AddServisForm asf = new AddServisForm();
        asf.setVisible(true);
    }//GEN-LAST:event_jButtonAutoServisActionPerformed

    private void jButtonRezervacijaDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRezervacijaDodajActionPerformed
        AddRezervacijaForm arf = new AddRezervacijaForm();
        arf.setVisible(true);
    }//GEN-LAST:event_jButtonRezervacijaDodajActionPerformed

    private void jButtonRezervacijaPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRezervacijaPretraziActionPerformed
        SearchRezervacijaForm srf = new SearchRezervacijaForm();
        srf.setVisible(true);
    }//GEN-LAST:event_jButtonRezervacijaPretraziActionPerformed

    private void jButtonRezervacijaIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRezervacijaIzmeniActionPerformed
        EditRezervacijaForm erf = new EditRezervacijaForm();
        erf.setVisible(true);
    }//GEN-LAST:event_jButtonRezervacijaIzmeniActionPerformed

    private void jButtonMarkaDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMarkaDodajActionPerformed
        AddMarkaForm adm = new AddMarkaForm();
        adm.setVisible(true);
    }//GEN-LAST:event_jButtonMarkaDodajActionPerformed

    private void jButtonMarkaPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMarkaPretraziActionPerformed
        SearchMarkaForm smf = new SearchMarkaForm();
        smf.setVisible(true);
    }//GEN-LAST:event_jButtonMarkaPretraziActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAutoDodaj;
    private javax.swing.JButton jButtonAutoPretrazi;
    private javax.swing.JButton jButtonAutoServis;
    private javax.swing.JButton jButtonMarkaDodaj;
    private javax.swing.JButton jButtonMarkaPretrazi;
    private javax.swing.JButton jButtonMusterijaDodaj;
    private javax.swing.JButton jButtonMusterijaIzmeni;
    private javax.swing.JButton jButtonMusterijaPretrazi;
    private javax.swing.JButton jButtonRezervacijaDodaj;
    private javax.swing.JButton jButtonRezervacijaIzmeni;
    private javax.swing.JButton jButtonRezervacijaPretrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelPozadina;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        this.getContentPane().setLayout(new BorderLayout());
        jLabelPozadina = new JLabel(new ImageIcon("src/main/java/com/amr/client/images/pozadina.jpeg"));
        this.getContentPane().add(jLabelPozadina, BorderLayout.CENTER);
    }

}
