package com.amr.client.view_edit;

import com.amr.client.controller.Controller;
import com.amr.common.domain.Automobil;
import com.amr.common.domain.Marka;
import com.amr.common.domain.Model;

/**
 * Klasa koja predstavlja formu za izmenu automobila
 *
 * @author Nebojsa Brankovic
 */
public class EditAutomobil2Form extends javax.swing.JFrame {

    /**
     * automobil koji se menja
     */
    private Automobil automobil;
    /**
     * nadforma
     */
    private EditAutomobilForm eaf;
    /**
     * klijentski kontroler
     */
    private Controller c;

    /**
     * Creates new form AddAutomobilForm
     *
     * @param eaf nadklasa/forma
     * @param automobil automobil koji je potrebno promeniti
     */
    public EditAutomobil2Form(EditAutomobilForm eaf, Automobil automobil) {
        initComponents();
        c = new Controller();
        this.eaf = eaf;
        this.automobil = automobil;
        prepareForm();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRegistracioniBroj = new javax.swing.JLabel();
        jTextFieldRegistracioniBroj = new javax.swing.JTextField();
        jLabelGodiste = new javax.swing.JLabel();
        jLabelBrojMotora = new javax.swing.JLabel();
        jTextFieldBrojMotora = new javax.swing.JTextField();
        jTextFieldBrojSasije = new javax.swing.JTextField();
        jLabelBrojSasije = new javax.swing.JLabel();
        jLabelBoja = new javax.swing.JLabel();
        jLabelKubikaza = new javax.swing.JLabel();
        jTextFieldKubikaza = new javax.swing.JTextField();
        jLabelKonjskaSnaga = new javax.swing.JLabel();
        jTextFieldKonjskaSnaga = new javax.swing.JTextField();
        jLabelTipMenjaca = new javax.swing.JLabel();
        jLabelMarka = new javax.swing.JLabel();
        jLabelModel = new javax.swing.JLabel();
        jTextFieldVlasnik = new javax.swing.JTextField();
        jLabelVlasnik = new javax.swing.JLabel();
        jButtonZapamti = new javax.swing.JButton();
        jButtonNazad = new javax.swing.JButton();
        jLabelPoslednjiServis = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextFieldPoslednjiServis = new javax.swing.JTextField();
        jTextFieldMarka = new javax.swing.JTextField();
        jTextFieldGodiste = new javax.swing.JTextField();
        jTextFieldBoja = new javax.swing.JTextField();
        jTextFieldTipMenjaca = new javax.swing.JTextField();
        jTextFieldModel = new javax.swing.JTextField();
        jTextFieldBrojCilindara = new javax.swing.JTextField();
        jLabelBrojCilindara = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Izmena poslednjeg servisa");

        jLabelRegistracioniBroj.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelRegistracioniBroj.setText("Registracioni broj");

        jTextFieldRegistracioniBroj.setEditable(false);
        jTextFieldRegistracioniBroj.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldRegistracioniBroj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRegistracioniBrojActionPerformed(evt);
            }
        });

        jLabelGodiste.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelGodiste.setText("Godiste");

        jLabelBrojMotora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelBrojMotora.setText("Broj motora");

        jTextFieldBrojMotora.setEditable(false);
        jTextFieldBrojMotora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextFieldBrojSasije.setEditable(false);
        jTextFieldBrojSasije.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabelBrojSasije.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelBrojSasije.setText("Broj sasije");

        jLabelBoja.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelBoja.setText("Boja");

        jLabelKubikaza.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelKubikaza.setText("Kubikaza (cc)");

        jTextFieldKubikaza.setEditable(false);
        jTextFieldKubikaza.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabelKonjskaSnaga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelKonjskaSnaga.setText("Snaga motora (hp)");

        jTextFieldKonjskaSnaga.setEditable(false);
        jTextFieldKonjskaSnaga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabelTipMenjaca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTipMenjaca.setText("Tip menjaca");

        jLabelMarka.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelMarka.setText("Marka");

        jLabelModel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelModel.setText("Model");

        jTextFieldVlasnik.setEditable(false);
        jTextFieldVlasnik.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabelVlasnik.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelVlasnik.setText("Vlasnik");

        jButtonZapamti.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonZapamti.setText("Zapamti");
        jButtonZapamti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZapamtiActionPerformed(evt);
            }
        });

        jButtonNazad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonNazad.setText("Nazad");
        jButtonNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNazadActionPerformed(evt);
            }
        });

        jLabelPoslednjiServis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelPoslednjiServis.setText("Poslednji servis (npr. 2021-05-30)");

        jTextFieldPoslednjiServis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextFieldMarka.setEditable(false);
        jTextFieldMarka.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextFieldGodiste.setEditable(false);
        jTextFieldGodiste.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextFieldBoja.setEditable(false);
        jTextFieldBoja.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextFieldTipMenjaca.setEditable(false);
        jTextFieldTipMenjaca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextFieldModel.setEditable(false);
        jTextFieldModel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextFieldBrojCilindara.setEditable(false);
        jTextFieldBrojCilindara.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabelBrojCilindara.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelBrojCilindara.setText("Broj cilindara");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelMarka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRegistracioniBroj, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jLabelModel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelVlasnik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelGodiste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldRegistracioniBroj, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jTextFieldVlasnik, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jTextFieldMarka)
                            .addComponent(jTextFieldGodiste)
                            .addComponent(jTextFieldModel)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonNazad)
                            .addGap(369, 369, 369)
                            .addComponent(jButtonZapamti))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelPoslednjiServis)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldPoslednjiServis, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTipMenjaca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTipMenjaca, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelBrojSasije, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelBoja, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelKubikaza, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelKonjskaSnaga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelBrojMotora, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldKonjskaSnaga, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(jTextFieldKubikaza)
                            .addComponent(jTextFieldBrojSasije)
                            .addComponent(jTextFieldBrojMotora)
                            .addComponent(jTextFieldBoja)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelBrojCilindara, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldBrojCilindara, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldRegistracioniBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRegistracioniBroj))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMarka)
                            .addComponent(jTextFieldMarka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelModel)
                            .addComponent(jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGodiste)
                            .addComponent(jTextFieldGodiste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldVlasnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelVlasnik)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldBrojMotora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBrojMotora))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldBrojSasije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBrojSasije))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBoja)
                            .addComponent(jTextFieldBoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldKubikaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelKubikaza))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldKonjskaSnaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelKonjskaSnaga))))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipMenjaca)
                    .addComponent(jTextFieldTipMenjaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBrojCilindara)
                    .addComponent(jTextFieldBrojCilindara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPoslednjiServis)
                    .addComponent(jTextFieldPoslednjiServis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNazad)
                    .addComponent(jButtonZapamti))
                .addGap(50, 50, 50))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldRegistracioniBrojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRegistracioniBrojActionPerformed
    }//GEN-LAST:event_jTextFieldRegistracioniBrojActionPerformed

    private void jButtonNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNazadActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonNazadActionPerformed

    private void jButtonZapamtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZapamtiActionPerformed
//        String poslednjiServis = jTextFieldPoslednjiServis.getText();
//        try {
//            automobil.setPoslednjiServis(new SimpleDateFormat("yyyy-MM-dd").parse(poslednjiServis));
//        } catch (ParseException ex) {
//            System.out.println("Greska u parsiranju datuma u EditAutomobil2Form.jButtonZapamtiActionPerformed()");
//        }
//        if (c.updateAutomobilPoslednjiServis(automobil)) {
//            JOptionPane.showMessageDialog(this, "Izvrsena izmena automobila: " + automobil.getRegistracioniBroj());
//            eaf.populateTable();
//            eaf.setVisible(true);
//            this.setVisible(false);
//            this.dispose();
//        } else {
//            JOptionPane.showMessageDialog(this, "Greska pri izmeni automobila : " + automobil.getRegistracioniBroj());
//        }


    }//GEN-LAST:event_jButtonZapamtiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNazad;
    private javax.swing.JButton jButtonZapamti;
    private javax.swing.JLabel jLabelBoja;
    private javax.swing.JLabel jLabelBrojCilindara;
    private javax.swing.JLabel jLabelBrojMotora;
    private javax.swing.JLabel jLabelBrojSasije;
    private javax.swing.JLabel jLabelGodiste;
    private javax.swing.JLabel jLabelKonjskaSnaga;
    private javax.swing.JLabel jLabelKubikaza;
    private javax.swing.JLabel jLabelMarka;
    private javax.swing.JLabel jLabelModel;
    private javax.swing.JLabel jLabelPoslednjiServis;
    private javax.swing.JLabel jLabelRegistracioniBroj;
    private javax.swing.JLabel jLabelTipMenjaca;
    private javax.swing.JLabel jLabelVlasnik;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldBoja;
    private javax.swing.JTextField jTextFieldBrojCilindara;
    private javax.swing.JTextField jTextFieldBrojMotora;
    private javax.swing.JTextField jTextFieldBrojSasije;
    private javax.swing.JTextField jTextFieldGodiste;
    private javax.swing.JTextField jTextFieldKonjskaSnaga;
    private javax.swing.JTextField jTextFieldKubikaza;
    private javax.swing.JTextField jTextFieldMarka;
    private javax.swing.JTextField jTextFieldModel;
    private javax.swing.JTextField jTextFieldPoslednjiServis;
    private javax.swing.JTextField jTextFieldRegistracioniBroj;
    private javax.swing.JTextField jTextFieldTipMenjaca;
    private javax.swing.JTextField jTextFieldVlasnik;
    // End of variables declaration//GEN-END:variables

    /**
     * Metoda za postavljanje forme
     */
    private void prepareForm() {
        jTextFieldBoja.setText(automobil.getBoja().toString());
        jTextFieldGodiste.setText(Integer.toString(automobil.getGodiste()));
        Marka ma = new Marka();
        ma.setMarkaId(automobil.getModel().getMarka().getMarkaId());
        jTextFieldMarka.setText(c.getNazivMarke(ma));
        Model m = new Model();
        m.setMarka(automobil.getModel().getMarka());
        m.setModelId(automobil.getModel().getModelId());
        jTextFieldModel.setText(c.getNazivModela(m));
        jTextFieldTipMenjaca.setText(automobil.getMenjac().toString());

        jTextFieldRegistracioniBroj.setText(automobil.getRegistracioniBroj());
        jTextFieldVlasnik.setText(automobil.getMusterija().getImeMusterije() + " "
                + automobil.getMusterija().getPrezimeMusterije());
        jTextFieldBrojMotora.setText(automobil.getBrojMotora());
        jTextFieldBrojSasije.setText(automobil.getBrojSasije());
        jTextFieldKubikaza.setText(Double.toString(automobil.getMotor().getKubikaza()));
        jTextFieldKonjskaSnaga.setText(Integer.toString(automobil.getMotor().getKonjskaSnaga()));
        jTextFieldBrojCilindara.setText(Integer.toString(automobil.getMotor().getBrojCilindara()));
    }
}
