package com.amr.client.view_edit;

import com.amr.client.controller.Controller;
import com.amr.client.tableModels.EditAutomobilTableModel;
import com.amr.common.domain.Automobil;
import java.util.List;
import javax.swing.JOptionPane;

/**
 * Klasa koja predstavlja formu za izmenu automobila
 *
 * @author Nebojsa Brankovic
 */
public class EditAutomobilForm extends javax.swing.JFrame {

    /**
     * klijentski kontroler
     */
    private Controller c;

    /**
     * Creates new form EditMusterijaForm
     */

    public EditAutomobilForm() {
        initComponents();
        c = new Controller();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRegistracioniBroj = new javax.swing.JLabel();
        jTextFieldRegistracioniBroj = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAutomobili = new javax.swing.JTable();
        jButtonIzmeni = new javax.swing.JButton();
        jButtonNazad = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Izmena automobila");

        jLabelRegistracioniBroj.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelRegistracioniBroj.setText("Registracioni broj");

        jTextFieldRegistracioniBroj.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldRegistracioniBroj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldRegistracioniBrojKeyReleased(evt);
            }
        });

        jTableAutomobili.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTableAutomobili.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableAutomobili.setRowHeight(30);
        jScrollPane1.setViewportView(jTableAutomobili);

        jButtonIzmeni.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonIzmeni.setText("Servis");
        jButtonIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniActionPerformed(evt);
            }
        });

        jButtonNazad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonNazad.setText("Nazad");
        jButtonNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNazadActionPerformed(evt);
            }
        });

        jButtonObrisi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonObrisi.setText("Obrisi");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1268, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabelRegistracioniBroj)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldRegistracioniBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButtonNazad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonObrisi)
                .addGap(63, 63, 63)
                .addComponent(jButtonIzmeni)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegistracioniBroj)
                    .addComponent(jTextFieldRegistracioniBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNazad)
                    .addComponent(jButtonObrisi)
                    .addComponent(jButtonIzmeni))
                .addGap(50, 50, 50))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldRegistracioniBrojKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRegistracioniBrojKeyReleased
        String filter = jTextFieldRegistracioniBroj.getText();
        List<Automobil> automobili = c.getAutomobiliFilter(filter);
        jTableAutomobili.setModel(new EditAutomobilTableModel(automobili));
    }//GEN-LAST:event_jTextFieldRegistracioniBrojKeyReleased

    private void jButtonIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniActionPerformed
        if (jTableAutomobili.getSelectedRow() != -1) {
            Automobil automobil = ((EditAutomobilTableModel) jTableAutomobili.getModel()).getAutomobili().get(jTableAutomobili.getSelectedRow());
            EditAutomobil2Form ea2f = new EditAutomobil2Form(this, automobil);
            this.setVisible(false);
            ea2f.setVisible(true);
            this.dispose();
            jTextFieldRegistracioniBroj.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Izaberite automobil koji zelite da izmenite.");
        }
    }//GEN-LAST:event_jButtonIzmeniActionPerformed

    private void jButtonNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNazadActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonNazadActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed

        if (jTableAutomobili.getSelectedRow() != -1) {
            int odgovor = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da obrisete automobil?");
            if (odgovor == 0) {
                Automobil automobil = ((EditAutomobilTableModel) jTableAutomobili.getModel()).getAutomobili()
                        .get(jTableAutomobili.getSelectedRow());
                if (c.deleteAutomobil(automobil)) {
                    JOptionPane.showMessageDialog(this, "Uspesno obrisan automobil: " + automobil.getRegistracioniBroj());
                    jTableAutomobili.setModel(new EditAutomobilTableModel(c.getAutomobili()));
                } else {
                    JOptionPane.showMessageDialog(this, "Greska pri brisanju automobila. Morate prvo obrisati rezervaciju"
                            + " za dati automobil.");
                }
            }
            jTextFieldRegistracioniBroj.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Izaberite automobil koji zelite da obrisete.");
        }
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    /**
     * Glavna metoda
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* jTextFieldFilters look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAutomobilForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAutomobilForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAutomobilForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAutomobilForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAutomobilForm().setVisible(true);
            }
        });
    }

    /**
     * Metoda koja popunjava tabelu podacima iz baze podataka
     */
    public void populateTable() {
        jTableAutomobili.setModel(new EditAutomobilTableModel(c.getAutomobili()));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzmeni;
    private javax.swing.JButton jButtonNazad;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JLabel jLabelRegistracioniBroj;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAutomobili;
    private javax.swing.JTextField jTextFieldRegistracioniBroj;
    // End of variables declaration//GEN-END:variables
}
