package com.amr.client.view_search;

import com.amr.client.controller.Controller;
import com.amr.client.tableModels.SearchAutomobilTableModel;
import com.amr.common.domain.Automobil;
import com.amr.common.domain.Servis;
import java.util.List;
import javax.swing.JOptionPane;

/**
 * Klasa koja predstavlja formu za pretragu automobila
 *
 * @author Nebojsa Brankovic
 */
public class SearchAutomobilForm extends javax.swing.JFrame {

    /**
     * Klijentski kontroler
     */
    private Controller c;

    /**
     * Creates new form SearchMusterijaForm
     */
    public SearchAutomobilForm() {
        initComponents();
        c = new Controller();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRegistracioniBroj = new javax.swing.JLabel();
        jTextFieldRegistracioniBroj = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAutomobili = new javax.swing.JTable();
        jButtonNazad = new javax.swing.JButton();
        jButtonServis = new javax.swing.JButton();
        jTextFieldServis = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretraga automobila");

        jLabelRegistracioniBroj.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelRegistracioniBroj.setText("Registracioni broj");

        jTextFieldRegistracioniBroj.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldRegistracioniBroj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldRegistracioniBrojKeyReleased(evt);
            }
        });

        jTableAutomobili.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTableAutomobili.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableAutomobili.setRowHeight(30);
        jScrollPane1.setViewportView(jTableAutomobili);

        jButtonNazad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonNazad.setText("Nazad");
        jButtonNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNazadActionPerformed(evt);
            }
        });

        jButtonServis.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonServis.setText("Servis");
        jButtonServis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonServisActionPerformed(evt);
            }
        });

        jTextFieldServis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldServis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldServisKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1268, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabelRegistracioniBroj)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldRegistracioniBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButtonNazad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonServis)
                .addGap(58, 58, 58)
                .addComponent(jTextFieldServis, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegistracioniBroj)
                    .addComponent(jTextFieldRegistracioniBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNazad)
                    .addComponent(jButtonServis)
                    .addComponent(jTextFieldServis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldRegistracioniBrojKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRegistracioniBrojKeyReleased
        String filter = jTextFieldRegistracioniBroj.getText();
        List<Automobil> automobili = c.getAutomobiliFilter(filter);
        jTableAutomobili.setModel(new SearchAutomobilTableModel(automobili));
    }//GEN-LAST:event_jTextFieldRegistracioniBrojKeyReleased

    private void jButtonNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNazadActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonNazadActionPerformed

    private void jButtonServisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonServisActionPerformed
        if (jTableAutomobili.getSelectedRow() != -1) {
            Automobil automobil = ((SearchAutomobilTableModel) jTableAutomobili.getModel()).getAutomobili().get(jTableAutomobili.getSelectedRow());
            Servis servis = new Servis();
            servis.setAutomobil(automobil);
            servis = c.getServis(servis);
            if (servis == null) {
                JOptionPane.showMessageDialog(this, "Za izabrani automobil ne postoji servis");
            } else {
                jTextFieldServis.setText(servis.getDatumServisa().toString());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Izaberite automobil");
        }
    }//GEN-LAST:event_jButtonServisActionPerformed

    private void jTextFieldServisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldServisKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldServisKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchAutomobilForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchAutomobilForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchAutomobilForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchAutomobilForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchAutomobilForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNazad;
    private javax.swing.JButton jButtonServis;
    private javax.swing.JLabel jLabelRegistracioniBroj;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAutomobili;
    private javax.swing.JTextField jTextFieldRegistracioniBroj;
    private javax.swing.JTextField jTextFieldServis;
    // End of variables declaration//GEN-END:variables

    /**
     * Metoda za popunjavanje tabele iz baze podataka
     */
    private void populateTable() {
        jTableAutomobili.setModel(new SearchAutomobilTableModel(c.getAutomobili()));
    }
}
