package com.amr.client.view_find;

import com.amr.client.controller.Controller;
import com.amr.client.tableModels.SearchAutomobilTableModel;
import com.amr.client.view_add.AddServisForm;
import com.amr.common.domain.Automobil;
import java.util.List;
import javax.swing.JOptionPane;

/**
 * Klasa koja predstavlja formu za vracanje automobila
 *
 * @author Nebojsa Brankovic
 */
public class GetAutomobilForm extends javax.swing.JFrame {

    /**
     * Nadklasa
     */
    private AddServisForm asf;
    /**
     * Klijentski kontroler
     */
    private Controller c;

    /**
     * Creates new form NadjiAutomobilForm
     * 
     * @param asf nadklasa/forma
     */
    public GetAutomobilForm(AddServisForm asf) {
        initComponents();
        c = new Controller();
        this.asf = asf;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFilter = new javax.swing.JLabel();
        jTextFieldFilter = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAutomobili = new javax.swing.JTable();
        jButtonNazad = new javax.swing.JButton();
        jButtonIzaberiAutomobil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Musterije");

        jLabelFilter.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelFilter.setText("Filter");

        jTextFieldFilter.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldFilterKeyReleased(evt);
            }
        });

        jTableAutomobili.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTableAutomobili.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableAutomobili.setRowHeight(30);
        jScrollPane1.setViewportView(jTableAutomobili);

        jButtonNazad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonNazad.setText("Nazad");
        jButtonNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNazadActionPerformed(evt);
            }
        });

        jButtonIzaberiAutomobil.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonIzaberiAutomobil.setText("Izaberi");
        jButtonIzaberiAutomobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzaberiAutomobilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1268, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabelFilter)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButtonNazad, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonIzaberiAutomobil, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFilter)
                    .addComponent(jTextFieldFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNazad)
                    .addComponent(jButtonIzaberiAutomobil))
                .addGap(50, 50, 50))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFilterKeyReleased
        String filter = jTextFieldFilter.getText();
        List<Automobil> automobili = c.getAutomobiliFilter(filter);
        jTableAutomobili.setModel(new SearchAutomobilTableModel(automobili));
    }//GEN-LAST:event_jTextFieldFilterKeyReleased

    private void jButtonNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNazadActionPerformed
        this.setVisible(false);
        asf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonNazadActionPerformed

    private void jButtonIzaberiAutomobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzaberiAutomobilActionPerformed
        if (jTableAutomobili.getSelectedRow() != -1) {
            Automobil automobil = ((SearchAutomobilTableModel) jTableAutomobili.getModel()).getAutomobili().get(jTableAutomobili.getSelectedRow());
            asf.setAutomobil(automobil);
            asf.setVisible(true);
            this.setVisible(false);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Izaberite automobil");
        }
    }//GEN-LAST:event_jButtonIzaberiAutomobilActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzaberiAutomobil;
    private javax.swing.JButton jButtonNazad;
    private javax.swing.JLabel jLabelFilter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAutomobili;
    private javax.swing.JTextField jTextFieldFilter;
    // End of variables declaration//GEN-END:variables

    /**
     * Metoda za popunjavanje tabele podacima iz baze podataka
     */
    public void populateTable() {
        jTableAutomobili.setModel(new SearchAutomobilTableModel(c.getAutomobili()));
    }

}
