package com.amr.common.communication;

/**
 * Enum klasa za sve sistemske operacije potrebne na klijentskoj strani
 *
 * @author Nebojsa Brankovic
 */
public enum Operation {
    CONNECT,
    LOGIN,
    USERNAME_EXISTS,
    AUTOMOBIL_EXISTS,
    SAVE_RADNIK,
    SAVE_MUSTERIJA,
    SAVE_MUSTERIJE,
    SAVE_MARKA,
    SAVE_AUTOMOBIL,
    SAVE_AUTOMOBILI,
    SAVE_REZERVACIJA,
    SAVE_REZERVACIJE,
    GET_RADNIK,
    GET_MODELID,
    GET_MARKA,
    GET_NAZIVMODELA,
    GET_NAZIVMARKE,
    GET_MARKE,
    GET_MODELI,
    GET_MODELIFNM,
    GET_MODELI2,
    GET_MUSTERIJEFILTER,
    GET_MUSTERIJE,
    GET_RADNICIFILTER,
    GET_RADNICI,
    GET_AUTOMOBILIFILTER,
    GET_AUTOMOBILI,
    GET_REZERVACIJEFILTER,
    GET_REZERVACIJE,
    DELETE_MUSTERIJA,
    DELETE_AUTOMOBIL,
    DELETE_REZERVACIJA,
    UPDATE_MUSTERIJA,
    UPDATE_AUTOMOBIL_POSLEDNJISERVIS,
    UPDATE_REZERVACIJA,
    QUIT,
    SAVE_MOTOR,
    GET_MOTOR,
    SAVE_SERVIS,
    GET_SERVIS
}
