package com.amr.client.view_add;

import com.amr.client.controller.Controller;
import com.amr.client.tableModels.AddMarkaTableModel;
import com.amr.common.domain.Marka;
import com.amr.common.domain.Model;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 * Klasa koja predstavlja formu za prikaz dodavanja marke
 *
 * @author Nebojsa Brankovic
 */
public class AddMarkaForm extends javax.swing.JFrame {

    /**
     * Marka koja se dodaje
     */
    private Marka marka;
    /**
     * Lista modela
     */
    private List<Model> modeli;
    /**
     * Klijentski kontroler
     */
    private Controller c;

    /**
     * Creates new form AddMarkaForm
     */
    public AddMarkaForm() {
        initComponents();
        c = new Controller();
        marka = new Marka();
        modeli = new ArrayList<>();
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNazivMarke = new javax.swing.JTextField();
        jLabelNazivMarkeObaveza = new javax.swing.JLabel();
        jPanelModel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNazivModela = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableModeli = new javax.swing.JTable();
        jButtonDodajModel = new javax.swing.JButton();
        jLabelNazivModelaObaveza = new javax.swing.JLabel();
        jButtonNazad = new javax.swing.JButton();
        jButtonZapamti = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dodavanje marke");
        setSize(new java.awt.Dimension(1280, 720));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Naziv marke");

        jTextFieldNazivMarke.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabelNazivMarkeObaveza.setForeground(new java.awt.Color(255, 0, 0));
        jLabelNazivMarkeObaveza.setText("Obavezno je uneti naziv marke!");

        jPanelModel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jPanelModel.setName(""); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Modeli");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Naziv modela");

        jTextFieldNazivModela.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTableModeli.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTableModeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Naziv marke", "Naziv modela"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableModeli.setRowHeight(30);
        jScrollPane1.setViewportView(jTableModeli);

        jButtonDodajModel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonDodajModel.setText("Dodaj model");
        jButtonDodajModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajModelActionPerformed(evt);
            }
        });

        jLabelNazivModelaObaveza.setForeground(new java.awt.Color(255, 0, 0));
        jLabelNazivModelaObaveza.setText("Obavezno je uneti naziv marke!");

        javax.swing.GroupLayout jPanelModelLayout = new javax.swing.GroupLayout(jPanelModel);
        jPanelModel.setLayout(jPanelModelLayout);
        jPanelModelLayout.setHorizontalGroup(
            jPanelModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonDodajModel))
                    .addGroup(jPanelModelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNazivModelaObaveza, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(jTextFieldNazivModela))))
                .addGap(107, 107, 107)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelModelLayout.setVerticalGroup(
            jPanelModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                    .addGroup(jPanelModelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(34, 34, 34)
                        .addGroup(jPanelModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldNazivModela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNazivModelaObaveza)
                        .addGap(72, 72, 72)
                        .addComponent(jButtonDodajModel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jButtonNazad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonNazad.setText("Nazad");
        jButtonNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNazadActionPerformed(evt);
            }
        });

        jButtonZapamti.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonZapamti.setText("Zapamti");
        jButtonZapamti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZapamtiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jTextFieldNazivMarke, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabelNazivMarkeObaveza, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanelModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButtonNazad)
                .addGap(1000, 1000, 1000)
                .addComponent(jButtonZapamti))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNazivMarke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabelNazivMarkeObaveza)
                .addGap(24, 24, 24)
                .addComponent(jPanelModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNazad)
                    .addComponent(jButtonZapamti)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDodajModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajModelActionPerformed
        if (isDataValid()) {
            jTextFieldNazivMarke.setEditable(false);
            if (marka.getNazivMarke().equals("")) {
                String nazivMarke = jTextFieldNazivMarke.getText().trim();
                marka.setNazivMarke(nazivMarke);
            }
            Model model = new Model();
            model.setNazivModela(jTextFieldNazivModela.getText().trim());
            model.setMarka(new Marka(marka.getNazivMarke()));
            modeli.add(model);
            marka.setModeli(modeli);
            ((AddMarkaTableModel) jTableModeli.getModel()).setMarka(marka);
        }
    }//GEN-LAST:event_jButtonDodajModelActionPerformed

    private void jButtonNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNazadActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonNazadActionPerformed

    private void jButtonZapamtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZapamtiActionPerformed
        if (marka.getModeli().size() > 0) {
            if (c.saveMarka(marka)) {
                JOptionPane.showMessageDialog(this, "Uspesno sacuvana marka");
                this.setVisible(false);
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Unesite modele");
        }
    }//GEN-LAST:event_jButtonZapamtiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajModel;
    private javax.swing.JButton jButtonNazad;
    private javax.swing.JButton jButtonZapamti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelNazivMarkeObaveza;
    private javax.swing.JLabel jLabelNazivModelaObaveza;
    private javax.swing.JPanel jPanelModel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableModeli;
    private javax.swing.JTextField jTextFieldNazivMarke;
    private javax.swing.JTextField jTextFieldNazivModela;
    // End of variables declaration//GEN-END:variables

    /**
     * Metoda za pripremu forme
     */
    private void prepareForm() {
        jLabelNazivMarkeObaveza.setVisible(false);
        jLabelNazivModelaObaveza.setVisible(false);

        jTableModeli.setModel(new AddMarkaTableModel(marka));
    }

    /**
     * Metoda koja ispituje da li je unos korektan
     *
     * @return validnost unosa
     */
    private boolean isDataValid() {
        if (jTextFieldNazivMarke.getText().trim().equals("")) {
            jLabelNazivMarkeObaveza.setVisible(true);
            return false;
        }
        if (jTextFieldNazivModela.getText().trim().equals("")) {
            jLabelNazivModelaObaveza.setVisible(true);
            return false;
        }
        return true;
    }

}
