package com.amr.client.view_add;

import com.amr.client.controller.Controller;
import com.amr.client.view_find.FindVlasnik2Form;
import com.amr.common.domain.Musterija;
import javax.swing.JOptionPane;

/**
 * Klasa koja predstavlja formu za unos musterije
 *
 * @author Nebojsa Brankovic
 */
public class AddMusterija3Form extends javax.swing.JFrame {

    /**
     * objekat nadklase(forme)
     */
    private FindVlasnik2Form nv2f;
    /**
     * Klijentrski kontroler
     */
    private Controller c;

    /**
     * Creates new form AddMusterijaForm
     */
    public AddMusterija3Form(FindVlasnik2Form nv2f) {
        initComponents();
        c = new Controller();
        this.nv2f = nv2f;
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelIme = new javax.swing.JLabel();
        jLabelPrezime = new javax.swing.JLabel();
        jLabelMail = new javax.swing.JLabel();
        jLabelBrojTelefona = new javax.swing.JLabel();
        jTextFieldMail = new javax.swing.JTextField();
        jTextFieldBrojTelefona = new javax.swing.JTextField();
        jTextFieldPrezime = new javax.swing.JTextField();
        jTextFieldIme = new javax.swing.JTextField();
        jButtonZapamti = new javax.swing.JButton();
        jButtonNazad = new javax.swing.JButton();
        jLabelImeObaveza = new javax.swing.JLabel();
        jLabelPrezimeObaveza = new javax.swing.JLabel();
        jLabelMailObaveza = new javax.swing.JLabel();
        jLabelBrojTelefonaObaveza = new javax.swing.JLabel();
        jTextFieldBrojTelefonaPrefiks = new javax.swing.JTextField();
        jLabelBrojTelefonaZnakovi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dodavanje musterije");

        jLabelIme.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelIme.setText("Ime");

        jLabelPrezime.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelPrezime.setText("Prezime");

        jLabelMail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelMail.setText("Mail");

        jLabelBrojTelefona.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelBrojTelefona.setText("Broj telefona");

        jTextFieldMail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldMail.setText("@gmail.com");

        jTextFieldBrojTelefona.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextFieldPrezime.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextFieldIme.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButtonZapamti.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonZapamti.setText("Zapamti");
        jButtonZapamti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZapamtiActionPerformed(evt);
            }
        });

        jButtonNazad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonNazad.setText("Nazad");
        jButtonNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNazadActionPerformed(evt);
            }
        });

        jLabelImeObaveza.setForeground(new java.awt.Color(255, 0, 0));
        jLabelImeObaveza.setText("Obavezno polje!");

        jLabelPrezimeObaveza.setForeground(new java.awt.Color(255, 0, 0));
        jLabelPrezimeObaveza.setText("Obavezno polje!");

        jLabelMailObaveza.setForeground(new java.awt.Color(255, 0, 0));
        jLabelMailObaveza.setText("Obavezno polje!");

        jLabelBrojTelefonaObaveza.setForeground(new java.awt.Color(255, 0, 0));
        jLabelBrojTelefonaObaveza.setText("Obavezno polje!");

        jTextFieldBrojTelefonaPrefiks.setEditable(false);
        jTextFieldBrojTelefonaPrefiks.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldBrojTelefonaPrefiks.setText("+381");

        jLabelBrojTelefonaZnakovi.setForeground(new java.awt.Color(255, 0, 0));
        jLabelBrojTelefonaZnakovi.setText("Dozvoljen unos iskljucivo brojeva!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNazad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonZapamti))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelIme)
                                    .addComponent(jLabelPrezime)
                                    .addComponent(jLabelMail))
                                .addGap(56, 56, 56))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelBrojTelefona)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelImeObaveza, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPrezimeObaveza, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMailObaveza, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIme)
                            .addComponent(jTextFieldPrezime)
                            .addComponent(jTextFieldMail)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldBrojTelefonaPrefiks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldBrojTelefona, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelBrojTelefonaObaveza)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelBrojTelefonaZnakovi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(823, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIme))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelImeObaveza)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrezime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPrezimeObaveza)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMailObaveza)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBrojTelefona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBrojTelefona)
                    .addComponent(jTextFieldBrojTelefonaPrefiks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBrojTelefonaObaveza)
                    .addComponent(jLabelBrojTelefonaZnakovi))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonZapamti)
                    .addComponent(jButtonNazad))
                .addContainerGap(310, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNazadActionPerformed
        this.setVisible(false);
        nv2f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonNazadActionPerformed

    private void jButtonZapamtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZapamtiActionPerformed
        if (isDataValid()) {
            Musterija musterija = new Musterija();
            musterija.setImeMusterije(jTextFieldIme.getText());
            musterija.setPrezimeMusterije(jTextFieldPrezime.getText());
            musterija.setMailMusterije(jTextFieldMail.getText());
            musterija.setTelefonMusterije("+381" + jTextFieldBrojTelefona.getText());
            if (c.saveMusterija(musterija)) {
                JOptionPane.showMessageDialog(this, "Uneta nova musterija: " + musterija.getImeMusterije()
                        + " " + musterija.getPrezimeMusterije());
                nv2f.populateTable();
                nv2f.setVisible(true);
                this.setVisible(false);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this, "Greska u pamcenju musterije");

            }
        }
    }//GEN-LAST:event_jButtonZapamtiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNazad;
    private javax.swing.JButton jButtonZapamti;
    private javax.swing.JLabel jLabelBrojTelefona;
    private javax.swing.JLabel jLabelBrojTelefonaObaveza;
    private javax.swing.JLabel jLabelBrojTelefonaZnakovi;
    private javax.swing.JLabel jLabelIme;
    private javax.swing.JLabel jLabelImeObaveza;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelMailObaveza;
    private javax.swing.JLabel jLabelPrezime;
    private javax.swing.JLabel jLabelPrezimeObaveza;
    private javax.swing.JTextField jTextFieldBrojTelefona;
    private javax.swing.JTextField jTextFieldBrojTelefonaPrefiks;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldMail;
    private javax.swing.JTextField jTextFieldPrezime;
    // End of variables declaration//GEN-END:variables

    /**
     * Metoda koja priprema formu
     */
    private void prepareForm() {
        jLabelImeObaveza.setVisible(false);
        jLabelPrezimeObaveza.setVisible(false);
        jLabelMailObaveza.setVisible(false);
        jLabelBrojTelefonaObaveza.setVisible(false);
        jLabelBrojTelefonaZnakovi.setVisible(false);
    }

    /**
     * Metoda koja ispituje validnost unosa korisnika
     *
     * @return validnost unosa
     */
    private boolean isDataValid() {
        if (jTextFieldIme == null || jTextFieldIme.getText().equals("")) {
            jLabelImeObaveza.setVisible(true);
            return false;
        } else {
            jLabelImeObaveza.setVisible(false);
        }
        if (jTextFieldPrezime == null || jTextFieldPrezime.getText().equals("")) {
            jLabelPrezimeObaveza.setVisible(true);
            return false;
        } else {
            jLabelPrezimeObaveza.setVisible(false);
        }
        if (jTextFieldMail == null || jTextFieldMail.getText().equals("") || jTextFieldMail.getText().equals("@gmail.com")) {
            jLabelMailObaveza.setVisible(true);
            return false;
        } else {
            jLabelMailObaveza.setVisible(false);
        }
        if (jTextFieldBrojTelefona == null || jTextFieldBrojTelefona.getText().equals("")) {
            jLabelBrojTelefonaObaveza.setVisible(true);
            return false;
        } else {
            jLabelBrojTelefonaObaveza.setVisible(false);
        }
        if (!isOk()) {
            jLabelBrojTelefonaZnakovi.setVisible(true);
            return false;
        } else {
            jLabelBrojTelefonaZnakovi.setVisible(false);
        }
        return true;
    }

    /**
     * Metoda koja ispituje da li je korisnik uneo odgovarajuci set karaktera
     *
     * @return validnost unosa
     */
    private boolean isOk() {
        char[] znakovi = new char[]{'a', 'A', 'b', 'B', 'c', 'C', 'd', 'D', 'e', 'E', 'f', 'F', 'g', 'G', 'h', 'H', 'i', 'I', 'g', 'G',
            'k', 'K', 'l', 'L', 'm', 'M', 'n', 'N', 'o', 'O', 'p', 'P', 'q', 'Q', 'r', 'R', 's', 'S', 't', 'T', 'u', 'U', 'v', 'V', 'w', 'W',
            'x', 'X', 'y', 'Y', 'z', 'Z', '-', '_', '+', '=', ',', '.', '<', '>', '/', '?', '"', '\\', '\'', '|', ':', ';', '[', '{', '}', ']',
            '!', '~', '`', '@', '#', '$', '%', '^', '&', '*', '(', ')'};
        char[] unos = jTextFieldBrojTelefona.getText().toCharArray();
        for (int i = 0; i < unos.length; i++) {
            for (int j = 0; j < znakovi.length; j++) {
                if (unos[i] == znakovi[j]) {
                    return false;
                }
            }
        }
        return true;
    }
}
