package com.amr.client.view_add;

import com.amr.client.controller.Controller;
import com.amr.client.tableModels.AddRezervacijaTableModel;
import com.amr.client.view_find.FindRadnikForm;
import com.amr.common.domain.Automobil;
import com.amr.common.domain.Radnik;
import com.amr.common.domain.Rezervacija;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 * Klasa koja predstavlja formu za dodavanje rezervacije
 *
 * @author Nebojsa Brankovic
 */
public class AddRezervacijaForm1 extends javax.swing.JFrame {

    /**
     * automobil za koji se pravi rezervacija
     */
    private Automobil automobil;
    /**
     * radnik koji treba da servisira taj auto
     */
    private Radnik radnik;
    /**
     * klijentski kontroler
     */
    private Controller c;

    /**
     * Creates new form AddAutomobilForm
     */
    public AddRezervacijaForm1() {
        initComponents();
        c = new Controller();
        this.automobil = null;
        this.radnik = null;
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDatumRezervacije = new javax.swing.JLabel();
        jTextFieldDatumRezervacije = new javax.swing.JTextField();
        jLabelDatumRezervacijaObaveza = new javax.swing.JLabel();
        jLabelRadnikObaveza = new javax.swing.JLabel();
        jLabelAutomobil = new javax.swing.JLabel();
        jTextFieldRadnik = new javax.swing.JTextField();
        jLabelAutomobilObaveza = new javax.swing.JLabel();
        jLabelSatLosUnos = new javax.swing.JLabel();
        jLabelTrajanjeServisaObaveza = new javax.swing.JLabel();
        jLabelRadnik = new javax.swing.JLabel();
        jLabelVremePocetkaServisa = new javax.swing.JLabel();
        jLabelTrajanjeServisa = new javax.swing.JLabel();
        jButtonZapamti = new javax.swing.JButton();
        jButtonNazad = new javax.swing.JButton();
        jTextFieldSat = new javax.swing.JTextField();
        jLabelSat = new javax.swing.JLabel();
        jLabelMinutLosUnos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMinut = new javax.swing.JTextField();
        jTextFieldTrajanjeServisa = new javax.swing.JTextField();
        jTextFieldAutomobil = new javax.swing.JTextField();
        jButtonNadjiAutomobil = new javax.swing.JButton();
        jButtonNadjiRadnika = new javax.swing.JButton();
        jLabelTrajanjeServisaLosUnos = new javax.swing.JLabel();
        jLabelDatumRezervacijeLosUnos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRezervacije = new javax.swing.JTable();
        jButtonDodaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dodavanje rezervacije");

        jLabelDatumRezervacije.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelDatumRezervacije.setText("Datum rezervacije (2023-03-24)");

        jTextFieldDatumRezervacije.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldDatumRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDatumRezervacijeActionPerformed(evt);
            }
        });

        jLabelDatumRezervacijaObaveza.setForeground(new java.awt.Color(255, 0, 0));
        jLabelDatumRezervacijaObaveza.setText("Obavezno polje!");

        jLabelRadnikObaveza.setForeground(new java.awt.Color(255, 0, 0));
        jLabelRadnikObaveza.setText("Obavezno polje!");

        jLabelAutomobil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelAutomobil.setText("Automobil");

        jTextFieldRadnik.setEditable(false);
        jTextFieldRadnik.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabelAutomobilObaveza.setForeground(new java.awt.Color(255, 0, 0));
        jLabelAutomobilObaveza.setText("Obavezno polje!");

        jLabelSatLosUnos.setForeground(new java.awt.Color(255, 0, 0));
        jLabelSatLosUnos.setText("Los unos!");

        jLabelTrajanjeServisaObaveza.setForeground(new java.awt.Color(255, 0, 0));
        jLabelTrajanjeServisaObaveza.setText("Obavezno polje!");

        jLabelRadnik.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelRadnik.setText("Radnik");

        jLabelVremePocetkaServisa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelVremePocetkaServisa.setText("Vreme pocetka servisa:");

        jLabelTrajanjeServisa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTrajanjeServisa.setText("Trajanje servisa (u minutama)");

        jButtonZapamti.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonZapamti.setText("Zapamti");
        jButtonZapamti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZapamtiActionPerformed(evt);
            }
        });

        jButtonNazad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonNazad.setText("Nazad");
        jButtonNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNazadActionPerformed(evt);
            }
        });

        jTextFieldSat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabelSat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelSat.setText("sat (11)");

        jLabelMinutLosUnos.setForeground(new java.awt.Color(255, 0, 0));
        jLabelMinutLosUnos.setText("Los unos!");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("minut (30)");

        jTextFieldMinut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextFieldTrajanjeServisa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextFieldAutomobil.setEditable(false);
        jTextFieldAutomobil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButtonNadjiAutomobil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonNadjiAutomobil.setText("Nadji automobil");
        jButtonNadjiAutomobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNadjiAutomobilActionPerformed(evt);
            }
        });

        jButtonNadjiRadnika.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonNadjiRadnika.setText("Nadji radnika");
        jButtonNadjiRadnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNadjiRadnikaActionPerformed(evt);
            }
        });

        jLabelTrajanjeServisaLosUnos.setForeground(new java.awt.Color(255, 0, 0));
        jLabelTrajanjeServisaLosUnos.setText("Los unos!");

        jLabelDatumRezervacijeLosUnos.setForeground(new java.awt.Color(255, 0, 0));
        jLabelDatumRezervacijeLosUnos.setText("Los unos!");

        jTableRezervacije.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTableRezervacije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableRezervacije.setRowHeight(30);
        jScrollPane1.setViewportView(jTableRezervacije);

        jButtonDodaj.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonDodaj.setText("Dodaj");
        jButtonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelRadnik, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelAutomobil, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabelVremePocetkaServisa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelDatumRezervacije, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelTrajanjeServisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelRadnikObaveza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelSat)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabelSatLosUnos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextFieldSat, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel2)
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextFieldMinut, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                                    .addComponent(jLabelMinutLosUnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldAutomobil, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonNadjiAutomobil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jLabelAutomobilObaveza, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldRadnik, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonNadjiRadnika, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelDatumRezervacijaObaveza)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabelDatumRezervacijeLosUnos))
                                            .addComponent(jTextFieldDatumRezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabelTrajanjeServisaObaveza)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabelTrajanjeServisaLosUnos))
                                            .addComponent(jTextFieldTrajanjeServisa, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(44, 367, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonNazad, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(520, 520, 520)
                                .addComponent(jButtonDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonZapamti, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDatumRezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDatumRezervacije))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDatumRezervacijaObaveza)
                    .addComponent(jLabelDatumRezervacijeLosUnos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVremePocetkaServisa)
                    .addComponent(jLabelSat)
                    .addComponent(jTextFieldSat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldMinut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSatLosUnos)
                    .addComponent(jLabelMinutLosUnos))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTrajanjeServisa)
                    .addComponent(jTextFieldTrajanjeServisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTrajanjeServisaObaveza)
                    .addComponent(jLabelTrajanjeServisaLosUnos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAutomobil)
                    .addComponent(jTextFieldAutomobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNadjiAutomobil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAutomobilObaveza)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRadnik)
                    .addComponent(jTextFieldRadnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNadjiRadnika)
                    .addComponent(jButtonDodaj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRadnikObaveza)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNazad)
                    .addComponent(jButtonZapamti))
                .addGap(60, 60, 60))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDatumRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDatumRezervacijeActionPerformed
    }//GEN-LAST:event_jTextFieldDatumRezervacijeActionPerformed

    private void jButtonNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNazadActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonNazadActionPerformed

    private void jButtonZapamtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZapamtiActionPerformed
        if (!((AddRezervacijaTableModel) jTableRezervacije.getModel()).getRezervacije().isEmpty()) {
            List<Rezervacija> rezervacije = ((AddRezervacijaTableModel) jTableRezervacije.getModel()).getRezervacije();
            if (!c.saveRezervacije(rezervacije)) {
                JOptionPane.showMessageDialog(this, "Greska pri unosu rezervacije."
                        + " Vec postoji rezervacija u tom periodu kod izabranog radnika", "Greska", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Unete rezervacije su zapamcene.");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Tabela je prazna");
        }
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonZapamtiActionPerformed

    private void jButtonNadjiAutomobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNadjiAutomobilActionPerformed
//        FindAutomobilForm naf = new FindAutomobilForm(this);
        this.setVisible(false);
//        naf.setVisible(true);
    }//GEN-LAST:event_jButtonNadjiAutomobilActionPerformed

    private void jButtonNadjiRadnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNadjiRadnikaActionPerformed
        FindRadnikForm nrf = new FindRadnikForm(this);
        this.setVisible(false);
        nrf.setVisible(true);
    }//GEN-LAST:event_jButtonNadjiRadnikaActionPerformed

    private void jButtonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajActionPerformed
        if (isDataValid()) {
            Rezervacija rezervacija = new Rezervacija();
            rezervacija.setTrajanjeServisa(Integer.parseInt(jTextFieldTrajanjeServisa.getText()));
            rezervacija.setAutomobil(automobil);
            rezervacija.setRadnik(radnik);
            String datumRezervacijeString = jTextFieldDatumRezervacije.getText().trim() + " " + jTextFieldSat.getText().trim()
                    + ":" + jTextFieldMinut.getText().trim() + ":00";
            Date datumRezervacije;
            try {
                datumRezervacije = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").parse(datumRezervacijeString);
                rezervacija.setPocetakServisa(datumRezervacije);
            } catch (ParseException ex) {
                System.out.println("Greska pri parsiranju kod jButtonZapamti u AddRezervacijaForm");
                return;
            }
            ((AddRezervacijaTableModel) jTableRezervacije.getModel()).addRezervacija(rezervacija);
            resetData();
        }
    }//GEN-LAST:event_jButtonDodajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRezervacijaForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRezervacijaForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRezervacijaForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRezervacijaForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRezervacijaForm1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JButton jButtonNadjiAutomobil;
    private javax.swing.JButton jButtonNadjiRadnika;
    private javax.swing.JButton jButtonNazad;
    private javax.swing.JButton jButtonZapamti;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAutomobil;
    private javax.swing.JLabel jLabelAutomobilObaveza;
    private javax.swing.JLabel jLabelDatumRezervacijaObaveza;
    private javax.swing.JLabel jLabelDatumRezervacije;
    private javax.swing.JLabel jLabelDatumRezervacijeLosUnos;
    private javax.swing.JLabel jLabelMinutLosUnos;
    private javax.swing.JLabel jLabelRadnik;
    private javax.swing.JLabel jLabelRadnikObaveza;
    private javax.swing.JLabel jLabelSat;
    private javax.swing.JLabel jLabelSatLosUnos;
    private javax.swing.JLabel jLabelTrajanjeServisa;
    private javax.swing.JLabel jLabelTrajanjeServisaLosUnos;
    private javax.swing.JLabel jLabelTrajanjeServisaObaveza;
    private javax.swing.JLabel jLabelVremePocetkaServisa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRezervacije;
    private javax.swing.JTextField jTextFieldAutomobil;
    private javax.swing.JTextField jTextFieldDatumRezervacije;
    private javax.swing.JTextField jTextFieldMinut;
    private javax.swing.JTextField jTextFieldRadnik;
    private javax.swing.JTextField jTextFieldSat;
    private javax.swing.JTextField jTextFieldTrajanjeServisa;
    // End of variables declaration//GEN-END:variables

    /**
     * Metoda za postavljanje forme
     */
    private void prepareForm() {
        jLabelDatumRezervacijaObaveza.setVisible(false);
        jLabelSatLosUnos.setVisible(false);
        jLabelMinutLosUnos.setVisible(false);
        jLabelTrajanjeServisaObaveza.setVisible(false);
        jLabelAutomobilObaveza.setVisible(false);
        jLabelRadnikObaveza.setVisible(false);
        jLabelDatumRezervacijeLosUnos.setVisible(false);
        jLabelTrajanjeServisaLosUnos.setVisible(false);

        jTableRezervacije.setModel(new AddRezervacijaTableModel());
    }

    /**
     * Metoda za postavljanje automobila
     *
     * @param automobil automobil za koji se pravi rezervacija
     */
    public void setAutomobil(Automobil automobil) {
        jTextFieldAutomobil.setText(automobil.getRegistracioniBroj());
        this.automobil = automobil;
    }

    /**
     * Metoda za postavljanje radnika koji ce servisirati auto
     *
     * @param radnik radnik koji ce servisirati auto
     */
    public void setRadnik(Radnik radnik) {
        jTextFieldRadnik.setText(radnik.getImeRadnika() + " " + radnik.getPrezimeRadnika());
        this.radnik = radnik;
    }

    /**
     * Metoda koja proverava validnost unosa
     *
     * @return validnost unosa
     */
    private boolean isDataValid() {
        if (jTextFieldDatumRezervacije == null || jTextFieldDatumRezervacije.getText().equals("")) {
            jLabelDatumRezervacijaObaveza.setVisible(true);
            return false;
        } else {
            jLabelDatumRezervacijaObaveza.setVisible(false);
        }
        if (!isOk2(jTextFieldDatumRezervacije)) {
            jLabelDatumRezervacijeLosUnos.setVisible(true);
            return false;
        } else {
            jLabelDatumRezervacijeLosUnos.setVisible(false);
        }
        if (jTextFieldSat == null || jTextFieldSat.getText().equals("")) {
            jLabelSatLosUnos.setVisible(true);
            return false;
        } else {
            jLabelSatLosUnos.setVisible(false);
        }
        if (!isOk(jTextFieldSat)) {
            jLabelSatLosUnos.setVisible(true);
            return false;
        } else {
            jLabelSatLosUnos.setVisible(false);
        }
        if (jTextFieldMinut == null || jTextFieldMinut.getText().equals("")) {
            jLabelMinutLosUnos.setVisible(true);
            return false;
        } else {
            jLabelMinutLosUnos.setVisible(false);
        }
        if (!isOk(jTextFieldMinut)) {
            jLabelMinutLosUnos.setVisible(true);
            return false;
        } else {
            jLabelMinutLosUnos.setVisible(false);
        }
        if (jTextFieldTrajanjeServisa == null || jTextFieldTrajanjeServisa.getText().equals("")) {
            jLabelTrajanjeServisaObaveza.setVisible(true);
            return false;
        } else {
            jLabelTrajanjeServisaObaveza.setVisible(false);
        }
        if (!isOk(jTextFieldTrajanjeServisa)) {
            jLabelTrajanjeServisaLosUnos.setVisible(true);
            return false;
        } else {
            jLabelTrajanjeServisaLosUnos.setVisible(false);
        }
        if (jTextFieldAutomobil == null || jTextFieldAutomobil.getText().equals("")) {
            jLabelAutomobilObaveza.setVisible(true);
            return false;
        } else {
            jLabelAutomobilObaveza.setVisible(false);
        }
        if (jTextFieldRadnik == null || jTextFieldRadnik.getText() == null) {
            jLabelRadnikObaveza.setVisible(true);
            return false;
        } else {
            jLabelRadnikObaveza.setVisible(false);
        }

        return true;
    }

    /**
     * Metoda koja proverava validnost unosa
     *
     * @param jtf unos
     * @return validnost unosa
     */
    public boolean isOk(JTextField jtf) {
        char[] znakovi = new char[]{'a', 'A', 'b', 'B', 'c', 'C', 'd', 'D', 'e', 'E', 'f', 'F', 'g', 'G', 'h', 'H', 'i', 'I', 'g', 'G',
            'k', 'K', 'l', 'L', 'm', 'M', 'n', 'N', 'o', 'O', 'p', 'P', 'q', 'Q', 'r', 'R', 's', 'S', 't', 'T', 'u', 'U', 'v', 'V', 'w', 'W',
            'x', 'X', 'y', 'Y', 'z', 'Z', '-', '_', '+', '=', ',', '.', '<', '>', '/', '?', '"', '\\', '\'', '|', ':', ';', '[', '{', '}', ']',
            '!', '~', '`', '@', '#', '$', '%', '^', '&', '*', '(', ')'};
        char[] unos = jtf.getText().toCharArray();
        for (int i = 0; i < unos.length; i++) {
            for (int j = 0; j < znakovi.length; j++) {
                if (unos[i] == znakovi[j]) {
                    return false;
                }
            }
        }
        return true;
    }

    /**
     * Metoda koja proverava validnost unosa
     *
     * @param jtf unos
     * @return validnost unosa
     */
    public boolean isOk2(JTextField jtf) {
        char[] znakovi = new char[]{'a', 'A', 'b', 'B', 'c', 'C', 'd', 'D', 'e', 'E', 'f', 'F', 'g', 'G', 'h', 'H', 'i', 'I', 'g', 'G',
            'k', 'K', 'l', 'L', 'm', 'M', 'n', 'N', 'o', 'O', 'p', 'P', 'q', 'Q', 'r', 'R', 's', 'S', 't', 'T', 'u', 'U', 'v', 'V', 'w', 'W',
            'x', 'X', 'y', 'Y', 'z', 'Z', '_', '+', '=', ',', '.', '<', '>', '/', '?', '"', '\\', '\'', '|', ':', ';', '[', '{', '}', ']',
            '!', '~', '`', '@', '#', '$', '%', '^', '&', '*', '(', ')'};
        char[] unos = jtf.getText().toCharArray();
        for (int i = 0; i < unos.length; i++) {
            for (int j = 0; j < znakovi.length; j++) {
                if (unos[i] == znakovi[j]) {
                    return false;
                }
            }
        }
        return true;
    }

    /**
     * Metoda koja prazni formu
     */
    private void emptyForm() {
        jTextFieldDatumRezervacije.setText("");
        jTextFieldSat.setText("");
        jTextFieldMinut.setText("");
        jTextFieldTrajanjeServisa.setText("");
        jTextFieldAutomobil.setText("");
        jTextFieldRadnik.setText("");
    }

    /**
     * Metoda koja vraca podatke na pocetne
     */
    private void resetData() {
        jLabelDatumRezervacijaObaveza.setVisible(false);
        jLabelSatLosUnos.setVisible(false);
        jLabelMinutLosUnos.setVisible(false);
        jLabelTrajanjeServisaObaveza.setVisible(false);
        jLabelAutomobilObaveza.setVisible(false);
        jLabelRadnikObaveza.setVisible(false);
        jLabelDatumRezervacijeLosUnos.setVisible(false);
        jLabelTrajanjeServisaLosUnos.setVisible(false);

        jTextFieldAutomobil.setText("");
        jTextFieldDatumRezervacije.setText("");
        jTextFieldMinut.setText("");
        jTextFieldRadnik.setText("");
        jTextFieldSat.setText("");
        jTextFieldTrajanjeServisa.setText("");

        this.automobil = null;
        this.radnik = null;
    }
}
