package com.amr.client.view_add;

import com.amr.client.controller.Controller;
import com.amr.client.view_find.GetAutomobilForm;
import com.amr.client.view_find.GetRadnikForm;
import com.amr.common.domain.Automobil;
import com.amr.common.domain.Radnik;
import com.amr.common.domain.Servis;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 * Klasa koja predstavlja formu za dodavanje servisa
 *
 * @author Nebojsa Brankovic
 */
public class AddServisForm extends javax.swing.JFrame {

    /**
     * automobil za koji se pravi servis
     */
    private Automobil automobil;
    /**
     * radnik koji servisira
     */
    private Radnik radnik;
    /**
     * klijentski kontroler
     */
    private Controller c;

    /**
     * Creates new form AddAutomobilForm
     */
    public AddServisForm() {
        initComponents();
        c = new Controller();
        automobil = null;
        radnik = null;
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelKIlometraza = new javax.swing.JLabel();
        jTextFieldKilometraza = new javax.swing.JTextField();
        jLabelOpis = new javax.swing.JLabel();
        jButtonZapamti = new javax.swing.JButton();
        jButtonNazad = new javax.swing.JButton();
        jLabelDatumServisa = new javax.swing.JLabel();
        jTextFieldDatumServisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOpis = new javax.swing.JTextArea();
        jLabelAutomobil = new javax.swing.JLabel();
        jTextFieldAutomobil = new javax.swing.JTextField();
        jButtonIzaberiAutomobil = new javax.swing.JButton();
        jLabelRadnik = new javax.swing.JLabel();
        jTextFieldRadnik = new javax.swing.JTextField();
        jButtonIzaberiRadnika = new javax.swing.JButton();
        jLabelDatumServisaObavezan = new javax.swing.JLabel();
        jLabelOpisObaveza = new javax.swing.JLabel();
        jLabelKilometrazaObavezan = new javax.swing.JLabel();
        jLabelAutomobilObaveza = new javax.swing.JLabel();
        jLabelRadnikObaveza = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Servis");

        jLabelKIlometraza.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelKIlometraza.setText("Kilometraza");

        jTextFieldKilometraza.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldKilometraza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKilometrazaActionPerformed(evt);
            }
        });

        jLabelOpis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelOpis.setText("Opis");

        jButtonZapamti.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonZapamti.setText("Zapamti");
        jButtonZapamti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZapamtiActionPerformed(evt);
            }
        });

        jButtonNazad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonNazad.setText("Nazad");
        jButtonNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNazadActionPerformed(evt);
            }
        });

        jLabelDatumServisa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelDatumServisa.setText("Datum servis (npr. 2021-05-30)");

        jTextFieldDatumServisa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextAreaOpis.setColumns(20);
        jTextAreaOpis.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOpis);

        jLabelAutomobil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelAutomobil.setText("Automobil");

        jTextFieldAutomobil.setEditable(false);
        jTextFieldAutomobil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButtonIzaberiAutomobil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonIzaberiAutomobil.setText("Izaberi");
        jButtonIzaberiAutomobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzaberiAutomobilActionPerformed(evt);
            }
        });

        jLabelRadnik.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelRadnik.setText("Radnik");

        jTextFieldRadnik.setEditable(false);
        jTextFieldRadnik.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButtonIzaberiRadnika.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonIzaberiRadnika.setText("Izaberi");
        jButtonIzaberiRadnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzaberiRadnikaActionPerformed(evt);
            }
        });

        jLabelDatumServisaObavezan.setForeground(new java.awt.Color(255, 0, 51));
        jLabelDatumServisaObavezan.setText("Obavezan unos!");

        jLabelOpisObaveza.setForeground(new java.awt.Color(255, 0, 51));
        jLabelOpisObaveza.setText("Obavezan unos!");

        jLabelKilometrazaObavezan.setForeground(new java.awt.Color(255, 0, 51));
        jLabelKilometrazaObavezan.setText("Obavezan unos!");

        jLabelAutomobilObaveza.setForeground(new java.awt.Color(255, 0, 51));
        jLabelAutomobilObaveza.setText("Obavezan unos!");

        jLabelRadnikObaveza.setForeground(new java.awt.Color(255, 0, 51));
        jLabelRadnikObaveza.setText("Obavezan unos!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNazad)
                        .addGap(369, 369, 369)
                        .addComponent(jButtonZapamti))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelRadnik, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelOpis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelKIlometraza, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDatumServisa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelAutomobil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldKilometraza, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldDatumServisa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                .addComponent(jLabelDatumServisaObavezan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelOpisObaveza, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelKilometrazaObavezan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelRadnikObaveza, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldAutomobil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(jTextFieldRadnik, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(jLabelAutomobilObaveza, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonIzaberiRadnika, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonIzaberiAutomobil, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDatumServisa)
                    .addComponent(jTextFieldDatumServisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDatumServisaObavezan)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelKIlometraza)
                    .addComponent(jTextFieldKilometraza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelKilometrazaObavezan)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOpis)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelOpisObaveza)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAutomobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAutomobil)
                    .addComponent(jButtonIzaberiAutomobil, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAutomobilObaveza)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRadnik)
                    .addComponent(jTextFieldRadnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIzaberiRadnika, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRadnikObaveza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNazad)
                    .addComponent(jButtonZapamti))
                .addGap(50, 50, 50))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldKilometrazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKilometrazaActionPerformed
    }//GEN-LAST:event_jTextFieldKilometrazaActionPerformed

    private void jButtonNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNazadActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonNazadActionPerformed

    private void jButtonZapamtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZapamtiActionPerformed
        if (isDataValid()) {
            try {
                Servis servis = new Servis();
                servis.setDatumServisa(new SimpleDateFormat("yyyy-MM-dd").parse(jTextFieldDatumServisa.getText().trim()));
                servis.setKilometraza(Integer.parseInt(jTextFieldKilometraza.getText()));
                servis.setOpis(jTextAreaOpis.getText());
                servis.setAutomobil(this.automobil);
                servis.setRadnik(this.radnik);
                if (c.saveServis(servis)) {
                    JOptionPane.showMessageDialog(this, "Uspesno dodat servis.");
                    this.setVisible(false);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Greska pri cuvanju servisa");
                }
            } catch (ParseException ex) {
                System.out.println("Greska pri parsiranju: " + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nedostajuce vrednosti");
        }
    }//GEN-LAST:event_jButtonZapamtiActionPerformed

    private void jButtonIzaberiAutomobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzaberiAutomobilActionPerformed
        GetAutomobilForm gaf = new GetAutomobilForm(this);
        gaf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonIzaberiAutomobilActionPerformed

    private void jButtonIzaberiRadnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzaberiRadnikaActionPerformed
        GetRadnikForm grf = new GetRadnikForm(this);
        grf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonIzaberiRadnikaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzaberiAutomobil;
    private javax.swing.JButton jButtonIzaberiRadnika;
    private javax.swing.JButton jButtonNazad;
    private javax.swing.JButton jButtonZapamti;
    private javax.swing.JLabel jLabelAutomobil;
    private javax.swing.JLabel jLabelAutomobilObaveza;
    private javax.swing.JLabel jLabelDatumServisa;
    private javax.swing.JLabel jLabelDatumServisaObavezan;
    private javax.swing.JLabel jLabelKIlometraza;
    private javax.swing.JLabel jLabelKilometrazaObavezan;
    private javax.swing.JLabel jLabelOpis;
    private javax.swing.JLabel jLabelOpisObaveza;
    private javax.swing.JLabel jLabelRadnik;
    private javax.swing.JLabel jLabelRadnikObaveza;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaOpis;
    private javax.swing.JTextField jTextFieldAutomobil;
    private javax.swing.JTextField jTextFieldDatumServisa;
    private javax.swing.JTextField jTextFieldKilometraza;
    private javax.swing.JTextField jTextFieldRadnik;
    // End of variables declaration//GEN-END:variables

    /**
     * Metoda za postavljanje forme
     */
    private void prepareForm() {
        jLabelDatumServisaObavezan.setVisible(false);
        jLabelKilometrazaObavezan.setVisible(false);
        jLabelOpisObaveza.setVisible(false);
        jLabelAutomobilObaveza.setVisible(false);
        jLabelRadnikObaveza.setVisible(false);
    }

    /**
     * Metoda za postavljanje automobila
     *
     * @param a automobil koji se postavlja
     */
    public void setAutomobil(Automobil a) {
        this.automobil = a;
        jTextFieldAutomobil.setText(a.getRegistracioniBroj());
    }

    /**
     * Metoda za postavljanje radnika
     *
     * @param r radnik koji se postavlja
     */
    public void setRadnik(Radnik r) {
        this.radnik = r;
        jTextFieldRadnik.setText(r.getImeRadnika() + " " + r.getPrezimeRadnika());
    }

    /**
     * Metoda koja proverava validnost unosa
     *
     * @return validnost unosa
     */
    private boolean isDataValid() {
        if (jTextFieldDatumServisa == null || jTextFieldDatumServisa.getText().equals("")) {
            jLabelDatumServisaObavezan.setVisible(true);
            return false;
        } else {
            jLabelDatumServisaObavezan.setVisible(false);
        }
        if (jTextFieldKilometraza == null || jTextFieldKilometraza.getText().equals("")) {
            jLabelKilometrazaObavezan.setVisible(true);
            return false;
        } else {
            jLabelKilometrazaObavezan.setVisible(false);
        }
        if (jTextAreaOpis == null || jTextAreaOpis.getText().equals("")) {
            jLabelOpisObaveza.setVisible(true);
            return false;
        } else {
            jLabelOpisObaveza.setVisible(false);
        }
        if (jTextFieldAutomobil == null || jTextFieldAutomobil.getText().equals("")) {
            jLabelAutomobilObaveza.setVisible(true);
            return false;
        } else {
            jLabelAutomobilObaveza.setVisible(false);
        }
        if (jTextFieldRadnik == null || jTextFieldRadnik.getText().equals("")) {
            jLabelRadnikObaveza.setVisible(true);
            return false;
        } else {
            jLabelRadnikObaveza.setVisible(false);
        }
        return true;
    }

}
