package com.amr.common.domain;

/**
 *
 * @author Nebojsa Brankovic
 */
public enum StrucnaSprema {
    CETIRI_RAZREDA_OSNOVNE_SKOLE,
    OSNOVNA_SKOLA,
    SREDNJA_SKOLA,
    OSNOVNE_TROGODISNJE_AKADEMSKE_STUDIJE,
    OSNOVNE_TROGODISNJE_STRUKOVNE_STUDIJE,
    SPECIJALISTICKE_STRUKOVNE_STUDIJE,
    OSNOVNE_CETVOROGODISNJE_AKADEMSKE_STUDIJE,
    INTEGRISANE_MASTER_STUDIJE, MASTER,
    MAGISTAR_NAUKA,
    SPECIJALIZACIJA_U_MEDICINI,
    SPECIJALISTICKE_AKADEMSKE_STUDIJE,
    DOKTOR_NAUKA
}
